### ISSUE TITLE
How to repeat the bot on a loop ?

### ISSUE THREAD

**Issue by Melons-le** [georgGrankvist/TelegramShiller9000#2]
Hello, I really appreciate your program and thank you for making it open source. I wanted to know by what means I could repeat the bot on loop? That is to say that it repeats the function every 30 minutes for example, without that I need to restart it

**Comment by georgGrankvist** [comment]
The program runs in an infinite loop already. You just have to execute it
and leave it running. To change how often the function repeats, you change
the field within the time.sleep function on row 39, defaulted to 1800
seconds (30 minutes).

**Comment by Melons-le** [comment]
Thank you very much, I never understood that the bot does this automatically. I thought 1800 was in milliseconds and that was only to indicate that the last index had been typed.

Ahah I've been looking for 3 days on all the forums. 

Thanks a lot !

**Comment by georgGrankvist** [comment]
No worries! There is an updated version that handles some common errors
that occur in some executions on an old hard drive of mine, I will try to
get it out in the coming days! :)
